This notebook creates a csv file containing the following: 
1.   audio id
2.   duration
3.   bits per sample
4.   gender
5.   lan of recording
6.   mother tongue

In [8]:
import pandas as pd
import json
import os
import glob

#Function to extract files from folder
def extract_files(path):
    all_files = []
    for root, dirs, files in os.walk(path):
        files = glob.glob(os.path.join(root,'*.json'))
        for f in files :
            all_files.append(os.path.abspath(f))
    return all_files


info = extract_files('C:/Users/Kalinda Siaminwe/Documents/4th year/Final year project/notebooks/json_files')

In [10]:
#check if the files are accessed successfully
filepath = info[0]

df = pd.read_json(filepath, lines=True)
df.head()

,date,recording_lang,origin,source,suffix,BitsPerSample,Format,file_type,speakers,durationMsec,...,speaker_name,version,sampleRate,user_id,NumChannels,name,location,device,androidID,mother_tongue
0,2022-08-24 19:21:01+00:00,toi,Zambia,/v03-mbtmvftlubvw,220824-212101_toi_0ae_elicit,16,vnd.wave,NaN,[],5558,...,Kabunda Mukando,/v03,16000,-1234995873,1,220824-212101_toi_0ae_elicit_0,"[-15.3928504, 28.32945]",SAMSUNG-SM-G9550,0aef04d19c311e5b,toi

In [17]:
#Create a list of all the json files
json_list = []

for file in info:
    with open(file) as f:
        for line in f:
            json_list.append(json.loads(line))

In [18]:
json_list[:2]

[{'date': '2022-08-24T19:21:01Z',
  'recording_lang': 'toi',
  'origin': 'Zambia ',
  'source': '/v03-mbtmvftlubvw',
  'suffix': '220824-212101_toi_0ae_elicit',
  'BitsPerSample': 16,
  'Format': 'vnd.wave',
  'file_type': None,
  'speakers': [],
  'durationMsec': 5558,
  'speaker_note': '',
  'speaker_gender': 'Male',
  'languages': [],
  'item_id': 'mbtmvftlubvw',
  'speaker_birth_year': 2000,
  'speaker_name': 'Kabunda Mukando',
  'version': '/v03',
  'sampleRate': 16000,
  'user_id': '-1234995873',
  'NumChannels': 1,
  'name': '220824-212101_toi_0ae_elicit_0',
  'location': [-15.3928504, 28.32945],
  'device': 'SAMSUNG-SM-G9550',
  'androidID': '0aef04d19c311e5b',
  'mother_tongue': 'toi'},
 {'date': '2022-08-24T19:21:01Z',
  'recording_lang': 'toi',
  'origin': 'Zambia ',
  'source': '/v03-rxrtiazcxchw',
  'suffix': '220824-212101_toi_0ae_elicit',
  'BitsPerSample': 16,
  'Format': 'vnd.wave',
  'file_type': None,
  'speakers': [],
  'durationMsec': 6034,
  'speaker_note': '',
  'speaker_gender': 'Male',
  'languages': [],
  'item_id': 'rxrtiazcxchw',
  'speaker_birth_year': 2000,
  'speaker_name': 'Kabunda Mukando',
  'version': '/v03',
  'sampleRate': 16000,
  'user_id': '-1234995873',
  'NumChannels': 1,
  'name': '220824-212101_toi_0ae_elicit_1',
  'location': [-15.3928504, 28.32945],
  'device': 'SAMSUNG-SM-G9550',
  'androidID': '0aef04d19c311e5b',
  'mother_tongue': 'toi'}]

In [19]:
json_files = pd.DataFrame(json_list)
json_files.head()

,date,recording_lang,origin,source,suffix,BitsPerSample,Format,file_type,speakers,durationMsec,...,speaker_name,version,sampleRate,user_id,NumChannels,name,location,device,androidID,mother_tongue
0,2022-08-24T19:21:01Z,toi,Zambia,/v03-mbtmvftlubvw,220824-212101_toi_0ae_elicit,16,vnd.wave,None,[],5558,...,Kabunda Mukando,/v03,16000,-1234995873,1,220824-212101_toi_0ae_elicit_0,"[-15.3928504, 28.32945]",SAMSUNG-SM-G9550,0aef04d19c311e5b,toi
1,2022-08-24T19:21:01Z,toi,Zambia,/v03-rxrtiazcxchw,220824-212101_toi_0ae_elicit,16,vnd.wave,None,[],6034,...,Kabunda Mukando,/v03,16000,-1234995873,1,220824-212101_toi_0ae_elicit_1,"[-15.3928504, 28.32945]",SAMSUNG-SM-G9550,0aef04d19c311e5b,toi
2,2022-08-24T19:21:01Z,toi,Zambia,/v03-ffnpjuwbgiit,220824-212101_toi_0ae_elicit,16,vnd.wave,None,[],3176,...,Kabunda Mukando,/v03,16000,-1234995873,1,220824-212101_toi_0ae_elicit_10,"[-15.3928504, 28.32945]",SAMSUNG-SM-G9550,0aef04d19c311e5b,toi
3,2022-08-24T19:21:01Z,toi,Zambia,/v03-lrhawlffxhgv,220824-212101_toi_0ae_elicit,16,vnd.wave,None,[],2858,...,Kabunda Mukando,/v03,16000,-1234995873,1,220824-212101_toi_0ae_elicit_11,"[-15.3928504, 28.32945]",SAMSUNG-SM-G9550,0aef04d19c311e5b,toi
4,2022-08-24T19:21:01Z,toi,Zambia,/v03-ktzmjefwpwou,220824-212101_toi_0ae_elicit,16,vnd.wave,None,[],5240,...,Kabunda Mukando,/v03,16000,-1234995873,1,220824-212101_toi_0ae_elicit_12,"[-15.3928504, 28.32945]",SAMSUNG-SM-G9550,0aef04d19c311e5b,toi

In [25]:
#make a copy of the dataframe
df = json_files.copy()

#drop the columns that are not needed
df.drop(['date', 'origin', 'source', 'suffix', 'Format', 'file_type', 'speakers', 'speaker_note', 'item_id', 'speaker_birth_year','speaker_name', 'languages', 'version', 'sampleRate', 'user_id', 'NumChannels', 'location', 'device', 'androidID'], axis=1, inplace=True)

In [26]:
#check the dataframe
df.head()

,recording_lang,BitsPerSample,durationMsec,speaker_gender,name,mother_tongue
0,toi,16,5558,Male,220824-212101_toi_0ae_elicit_0,toi
1,toi,16,6034,Male,220824-212101_toi_0ae_elicit_1,toi
2,toi,16,3176,Male,220824-212101_toi_0ae_elicit_10,toi
3,toi,16,2858,Male,220824-212101_toi_0ae_elicit_11,toi
4,toi,16,5240,Male,220824-212101_toi_0ae_elicit_12,toi

In [27]:
#rename the column name to audio_id
df.rename(columns = {'name':'audio_id'}, inplace = True)
df.head()

,recording_lang,BitsPerSample,durationMsec,speaker_gender,audio_id,mother_tongue
0,toi,16,5558,Male,220824-212101_toi_0ae_elicit_0,toi
1,toi,16,6034,Male,220824-212101_toi_0ae_elicit_1,toi
2,toi,16,3176,Male,220824-212101_toi_0ae_elicit_10,toi
3,toi,16,2858,Male,220824-212101_toi_0ae_elicit_11,toi
4,toi,16,5240,Male,220824-212101_toi_0ae_elicit_12,toi

In [28]:
#rearange the columns
df = df[['audio_id', 'recording_lang', 'BitsPerSample','durationMsec', 'speaker_gender', 'mother_tongue']]
df.head()

,audio_id,recording_lang,BitsPerSample,durationMsec,speaker_gender,mother_tongue
0,220824-212101_toi_0ae_elicit_0,toi,16,5558,Male,toi
1,220824-212101_toi_0ae_elicit_1,toi,16,6034,Male,toi
2,220824-212101_toi_0ae_elicit_10,toi,16,3176,Male,toi
3,220824-212101_toi_0ae_elicit_11,toi,16,2858,Male,toi
4,220824-212101_toi_0ae_elicit_12,toi,16,5240,Male,toi

In [30]:
#get sum of durationMsec
df['durationMsec'].sum()

20683313

In [29]:
#save the dataframe as a csv file
df.to_csv('recordings_info.csv', index=False)